variable "aws_region" {
    description = "AWS region for all resources (Athena/Glue are regional). CloudFront is global; ACM must be us-east-1 regardless of this value."
    type        = string
    default     = "us-east-1"
}

variable "suffix" {
    description = "Suffix appended to globally-unique resources (e.g. the S3 lake and web buckets). If left empty, a random 8-char hex suffix is generated."
    type        = string
    default     = ""
}

variable "fivetran_aws_account_id" {
    description = "Fivetran's AWS account ID, used as the trust principal for the Fivetran assume role."
    type        = string
    default     = "834469178297"
}

variable "fivetran_external_id" {
    description = "External ID generated by Fivetran when configuring the destination. Paste the value Fivetran provides on the destination setup screen."
    type        = string
    sensitive   = true
}

variable "dbt_iam_user_arn" {
    description = "ARN of the IAM user (created manually) that the dbt runner uses to assume the linernotes-odi-dbt role. Example: arn:aws:iam::123456789012:user/dbt-runner"
    type        = string
}

variable "domain_name" {
    description = "Optional custom domain for the SPA (e.g. linernotes.example.com). If set, an ACM certificate and CloudFront alias are provisioned. Leave empty to use the auto-assigned CloudFront domain."
    type        = string
    default     = ""
}

variable "hosted_zone_id" {
    description = "Route53 hosted zone ID for the domain in var.domain_name. Required only when var.domain_name is set. If left empty, no Route53 record is created."
    type        = string
    default     = ""
}

variable "allowed_origins" {
    description = "List of origins permitted for CORS on the lake bucket. Used for any future API or direct-from-browser Athena queries."
    type        = list(string)
    default     = ["*"]
}

variable "tags" {
    description = "Default tags applied to every resource."
    type        = map(string)
    default = {
        Project     = "LinerNotes-ODI-Demo"
        Owner       = "Liner Notes Demo"
        Environment = "dev"
    }
}
